name: Ci

# Triggers
on:
  push:
    branches: ["master"]
  workflow_dispatch:

# What to do when triggered
jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Unit test
        run: npm run test:unit

  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Integration test
        run: npm run test:integration
