name: CI

#triggers
on: push

# what do when triggered
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - name: install dependencies
       run: npm install
       - name: unit test
       run: npm run test:unit
       - name: integrations test
       run: npm run test:integration
       