name: CI

on:
  push:
    branches:
      - main    # Triggers the workflow on push to the main branch
      - develop # Optional: Add any other branches you'd like to monitor

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - uses: actions/checkout@v4
      
      # Set up the environment (optional, customize according to your project)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x' # Specify the Node.js version

      # Install dependencies
      - name: Install dependencies
        run: npm install # Change this if your project uses a different package manager (e.g., yarn install)

      # Run tests
      - name: Run tests
        run: npm test # Change this if your project has a different test command

      # Build the project (optional, depending on your project)
      - name: Build project
        run: npm run build # Modify this if your project has a specific build command

      # Deploy or other steps (optional)
      # - name: Deploy
      #   run: npm run deploy # Add deployment steps if necessary
